# Generated by Django 4.2.3 on 2023-07-27 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_tswift_taylors_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='tswift',
            name='taylors_version',
            field=models.BooleanField(default=False),
        ),
    ]
