# Generated by Django 4.2.3 on 2023-07-27 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_tswift_taylors_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('tswift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.tswift')),
            ],
        ),
    ]
