# Generated by Django 4.2.3 on 2023-07-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_datinghistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='tswift',
            name='awards',
            field=models.ManyToManyField(to='main_app.award'),
        ),
    ]
